### PR TITLE
Fix typo in keycode name

### PR DESCRIPTION
**Pull request by dkm**
Fix a simple typo in a media keycode name.

### CODE REVIEW

**Comment by TeXitoi** [comment]
Thanks.

Can you add a note in the changelog? Something like "breaking change: keycode is renamed keycode to fix a typo"?

**Comment by dkm** [comment]
Sure. Do you want me to create a new entry in the CHANGELOG.md or simply add a point in the existing one, below action?

**Comment by TeXitoi** [comment]
Adding a point in the v0.2.0 breaking change list.

**Review by TeXitoi — APPROVED** [review]

**Comment by TeXitoi** [comment]
Thanks

**Comment by dkm** [comment]
thanks  ! I see that I did not squash it quickly enough (edit from phone, could not find an easy way to do it), sorry for the log...

**Comment by TeXitoi** [comment]
I squashed it in the merge interface.

**Comment by dkm** [comment]
Yes, but commit message is not "optimal" :)

**Pull request merged**
